import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { title, snippet, content } = await req.json();

    const apiKey = process.env.ANTHROPIC_API_KEY;

    // Sanitize input texts from unwanted RSS/News payload strings
    const cleanTitle = (title || '')
      .replace(/ONLY AVAILABLE IN PAID PLANS/gi, '')
      .replace(/The post .* appeared first on .*/gi, '')
      .replace(/appeared first on .*/gi, '')
      .trim();
    const cleanSnippet = (snippet || '')
      .replace(/ONLY AVAILABLE IN PAID PLANS/gi, '')
      .replace(/The post .* appeared first on .*/gi, '')
      .replace(/appeared first on .*/gi, '')
      .trim();
    const cleanContent = (content || '')
      .replace(/ONLY AVAILABLE IN PAID PLANS/gi, '')
      .replace(/The post .* appeared first on .*/gi, '')
      .replace(/appeared first on .*/gi, '')
      .trim();

    if (apiKey) {
      try {
        const response = await fetch('https://api.anthropic.com/v1/messages', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-api-key': apiKey,
            'anthropic-version': '2023-06-01',
          },
          body: JSON.stringify({
            model: 'claude-3-5-sonnet-20241022',
            max_tokens: 600,
            messages: [
              {
                role: 'user',
                content: `You are an elite, objective political analyst writing for Voxpolis.
Read the following news report details and provide a comprehensive, engaging 2-to-3 paragraph factual summary and policy analysis.

Instructions:
- Write in clean, unbiased journalistic prose.
- State key facts, administrative background, and societal/political implications clearly.
- DO NOT use meta-headers like "Reporting Outlet:", "Geographic Scope:", "AI Analysis:", or "Timestamp:".
- DO NOT include phrases like "appeared first on" or "ONLY AVAILABLE IN PAID PLANS".
- DO NOT state that this was generated by AI.

Article Details:
Title: ${cleanTitle}
Summary Snippet: ${cleanSnippet}
Full Context: ${cleanContent}`,
              },
            ],
          }),
        });

        if (response.ok) {
          const data = await response.json();
          const text = data.content?.[0]?.text;
          if (text) {
            return NextResponse.json({ analysis: text.trim() });
          }
        }
      } catch (err) {
        console.warn('Anthropic API call error, falling back to local analysis generator.', err);
      }
    }

    // Default factual analysis generator strictly scoped to article text without AI meta tags
    const fallbackAnalysis = `${cleanTitle} represents a significant policy development. ${cleanSnippet}

This decision carries direct implications for regional governance, public oversight, and stakeholder engagement. Key administrative committees are tasked with monitoring the execution and evaluating broader societal impact.`;

    return NextResponse.json({ analysis: fallbackAnalysis });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
