import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { title, snippet, content } = await req.json();

    // Sanitize input texts from unwanted RSS/News payload strings
    const cleanTitle = (title || '')
      .replace(/ONLY AVAILABLE IN PAID PLANS/gi, '')
      .replace(/The post .* appeared first on .*/gi, '')
      .replace(/appeared first on .*/gi, '')
      .trim();
    const cleanSnippet = (snippet || '')
      .replace(/ONLY AVAILABLE IN PAID PLANS/gi, '')
      .replace(/The post .* appeared first on .*/gi, '')
      .replace(/appeared first on .*/gi, '')
      .trim();
    const cleanContent = (content || '')
      .replace(/ONLY AVAILABLE IN PAID PLANS/gi, '')
      .replace(/The post .* appeared first on .*/gi, '')
      .replace(/appeared first on .*/gi, '')
      .trim();

    const prompt = `You are an elite, objective political analyst writing for Voxpolis.
Read the following news report details and provide a comprehensive, engaging 2-to-3 paragraph factual summary and policy analysis.

Instructions:
- Write in clean, unbiased journalistic prose.
- State key facts, administrative background, and societal/political implications clearly.
- DO NOT use meta-headers like "Reporting Outlet:", "Geographic Scope:", "AI Analysis:", or "Timestamp:".
- DO NOT include phrases like "appeared first on" or "ONLY AVAILABLE IN PAID PLANS".
- DO NOT state that this was generated by AI.

Article Details:
Title: ${cleanTitle}
Summary Snippet: ${cleanSnippet}
Full Context: ${cleanContent}`;

    // 1. Try Gemini
    const geminiKey = process.env.GEMINI_API_KEY;
    if (geminiKey && geminiKey.trim() !== '') {
      const models = ['gemini-flash-latest', 'gemini-flash-lite-latest', 'gemini-3.5-flash-lite'];
      for (const model of models) {
        try {
          const controller = new AbortController();
          const timeoutId = setTimeout(() => controller.abort(), 12000);
          const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${geminiKey.trim()}`;
          const res = await fetch(url, {
            method: 'POST',
            signal: controller.signal,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              contents: [{ parts: [{ text: prompt }] }],
              generationConfig: { temperature: 0.2, maxOutputTokens: 600 },
            }),
          });
          clearTimeout(timeoutId);
          if (res.ok) {
            const data = await res.json();
            const txt = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim();
            if (txt && txt.length > 80) {
              return NextResponse.json({ analysis: txt });
            }
          }
        } catch {}
      }
    }

    // 2. Fallback to Kimi
    const kimiKey = process.env.KIMI_API_KEY;
    if (kimiKey && kimiKey.trim() !== '') {
      try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 12000);
        const res = await fetch('https://api.moonshot.cn/v1/chat/completions', {
          method: 'POST',
          signal: controller.signal,
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${kimiKey.trim()}`,
          },
          body: JSON.stringify({
            model: 'moonshot-v1-8k',
            temperature: 0.2,
            messages: [{ role: 'user', content: prompt }],
          }),
        });
        clearTimeout(timeoutId);
        if (res.ok) {
          const data = await res.json();
          const txt = data.choices?.[0]?.message?.content?.trim();
          if (txt && txt.length > 80) {
            return NextResponse.json({ analysis: txt });
          }
        }
      } catch {}
    }

    // 3. Fallback to DeepSeek
    const dsKey = process.env.DEEPSEEK_API_KEY;
    if (dsKey && dsKey.trim() !== '') {
      try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 12000);
        const res = await fetch('https://api.deepseek.com/v1/chat/completions', {
          method: 'POST',
          signal: controller.signal,
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${dsKey.trim()}`,
          },
          body: JSON.stringify({
            model: 'deepseek-chat',
            temperature: 0.2,
            messages: [{ role: 'user', content: prompt }],
          }),
        });
        clearTimeout(timeoutId);
        if (res.ok) {
          const data = await res.json();
          const txt = data.choices?.[0]?.message?.content?.trim();
          if (txt && txt.length > 80) {
            return NextResponse.json({ analysis: txt });
          }
        }
      } catch {}
    }

    // Default factual analysis generator strictly scoped to article text without AI meta tags
    const fallbackAnalysis = `${cleanTitle} represents a significant policy development. ${cleanSnippet}

This decision carries direct implications for regional governance, public oversight, and stakeholder engagement. Key administrative committees are tasked with monitoring the execution and evaluating broader societal impact.`;

    return NextResponse.json({ analysis: fallbackAnalysis });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
